apiVersion: v1
data:
  DB_HOST: bG9jYWxob3N0
  DB_NAME: dG9kb2FwcA==
  DB_PASSWORD: dG9kb2FwcA==
  DB_PORT: NTQzMw==
  DB_USER: cG9zdGdyZXM=
  PORT: ODAwMA==
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret
